# 📓 Notebook 03: Data Preprocessing

## 🎯 Objective

Data preprocessing is a crucial stage in the machine learning pipeline. Raw datasets often contain categorical variables, inconsistent formats, and features that require transformation before they can be used by machine learning algorithms.

The objective of this notebook is to prepare the hospital readmission dataset for predictive modeling by performing the necessary preprocessing steps.

The preprocessing tasks include:

- Loading the cleaned dataset.
- Identifying numerical and categorical features.
- Encoding categorical variables.
- Scaling numerical features.
- Preparing the target variable.
- Splitting the dataset into training and testing sets.
- Building a preprocessing pipeline for reproducibility.

The processed dataset generated in this notebook will be used for model training in the next phase of the project.

Notebook 03 – Data Preprocessing

Step 1 - Import Libraries

Step 2 - Load Dataset

Step 3 - Understand Feature Types

Step 4 - Separate Features and Target

Step 5 - Encode Target Variable

Step 6 - Encode Categorical Features

Step 7 - Scale Numerical Features

Step 8 - Train-Test Split

Step 9 - Save Processed Dataset

Step 10 - Summary

Step 11 - Next Steps

---
# 📖 Step 1: Import Libraries
---

## 🎯 Objective

Several libraries are required to perform data preprocessing before building machine learning models.

These libraries provide functionalities for:

- Data manipulation
- Feature encoding
- Feature scaling
- Train-test splitting
- Saving processed datasets

In [2]:
# ============================================================
# Import Required Libraries
# ============================================================

# Data Manipulation
import pandas as pd
import numpy as np

# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# Dataset Splitting
from sklearn.model_selection import train_test_split

---
# 📖 Step 2: Load Dataset
---

## 🎯 Objective

Load the original hospital readmission dataset into a Pandas DataFrame.

The dataset loaded here will undergo preprocessing before being used for machine learning model development.

In [3]:
# ============================================================
# Load Dataset
# ============================================================

# Read the dataset
df = pd.read_csv("../data/raw/hospital_readmissions.csv")

# Display the first five records
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

## 🔍 Observations

The dataset has been loaded successfully.

The first five records confirm that all features have been imported correctly and are ready for preprocessing.

## 📌 Conclusion

The dataset is now available for preprocessing.

---
# 📖 Step 3: Identify Numerical and Categorical Features
---

## 🎯 Objective

Machine learning algorithms process numerical data directly, whereas categorical features require transformation before model training.

Before preprocessing, it is important to identify which columns are numerical and which are categorical.

This classification helps determine the appropriate preprocessing technique for each feature.

In [4]:
# ============================================================
# Identify Numerical and Categorical Features
# ============================================================

categorical_columns = df.select_dtypes(include=["object", "string"]).columns
numerical_columns = df.select_dtypes(include=["number"]).columns

# Display numerical features
print("Numerical Features:\n")
print(numerical_columns)

print("\n")

# Display categorical features
print("Categorical Features:\n")
print(categorical_columns)

Numerical Features:

Index(['time_in_hospital', 'n_lab_procedures', 'n_procedures', 'n_medications',
       'n_outpatient', 'n_inpatient', 'n_emergency'],
      dtype='str')


Categorical Features:

Index(['age', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3',
       'glucose_test', 'A1Ctest', 'change', 'diabetes_med', 'readmitted'],
      dtype='str')

## 🔍 Observations

The dataset consists of both numerical and categorical features.

### Numerical Features

The following seven features are numerical:

- `time_in_hospital`
- `n_lab_procedures`
- `n_procedures`
- `n_medications`
- `n_outpatient`
- `n_inpatient`
- `n_emergency`

These features contain quantitative information about patient hospitalization, medical procedures, medication usage, and previous healthcare utilization. Most machine learning algorithms can process these features directly, although feature scaling may be required.

### Categorical Features

The dataset contains ten categorical features:

- `age`
- `medical_specialty`
- `diag_1`
- `diag_2`
- `diag_3`
- `glucose_test`
- `A1Ctest`
- `change`
- `diabetes_med`
- `readmitted`

These features represent demographic information, medical diagnoses, laboratory test results, and treatment-related categories. Since machine learning algorithms cannot directly process categorical data, these features will require encoding during preprocessing.

Among these categorical features, **`readmitted`** is the target variable that the machine learning model will predict.

## 📌 Conclusion

The dataset contains a combination of numerical and categorical features. Numerical features will be prepared through feature scaling where appropriate, while categorical features will be converted into numerical representations using suitable encoding techniques.

The next step is to separate the input features from the target variable before applying preprocessing transformations.

---
# 📖 Step 4: Separate Features and Target Variable
---

## 🎯 Objective

Before building a machine learning model, the dataset must be divided into two components:

- **Input Features (`X`)** – Variables used by the model to make predictions.
- **Target Variable (`y`)** – The output that the model learns to predict.

Separating the dataset into features and the target variable ensures that the machine learning algorithm is trained using only the relevant input variables while evaluating predictions against the correct output.

In [5]:
# ============================================================
# Separate Features and Target Variable
# ============================================================

# Create the feature matrix (X)
X = df.drop("readmitted", axis=1)

# Create the target variable (y)
y = df["readmitted"]

# Display the shape of the feature matrix
print("Feature Matrix Shape:", X.shape)

# Display the shape of the target variable
print("Target Variable Shape:", y.shape)

# Display the first five rows of the feature matrix
X.head()

Feature Matrix Shape: (25000, 16)
Target Variable Shape: (25000,)

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes

## 🔍 Observations

After separating the dataset:

- The feature matrix (`X`) contains all predictor variables except the target.
- The target variable (`y`) contains the hospital readmission status.
- The feature matrix has **25,000 rows** and **16 input features**.
- The target variable contains **25,000 records**, with one label corresponding to each patient.

This separation ensures that the machine learning model learns from the predictor variables while using the target variable as the expected output.

## 📌 Conclusion

The dataset has been successfully separated into input features (`X`) and the target variable (`y`). This structure is required before applying encoding, feature scaling, and train-test splitting.

---
# 📖 Step 5A: Encode the Target Variable
---

## 🎯 Objective

The target variable (`readmitted`) contains categorical values (`Yes` and `No`). Machine learning algorithms require the target variable to be in numerical form before training.

In this step, we use **LabelEncoder** to convert the target labels into numerical values.

This transformation is only applied to the target variable because it represents class labels rather than input features.

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/raw/hospital_readmissions.csv")

df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [8]:
numerical_columns = df.select_dtypes(include=["number"]).columns
categorical_columns = df.select_dtypes(include=["object", "string"]).columns

print(numerical_columns)
print(categorical_columns)

Index(['time_in_hospital', 'n_lab_procedures', 'n_procedures', 'n_medications',
       'n_outpatient', 'n_inpatient', 'n_emergency'],
      dtype='str')
Index(['age', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3',
       'glucose_test', 'A1Ctest', 'change', 'diabetes_med', 'readmitted'],
      dtype='str')

In [9]:
X = df.drop("readmitted", axis=1)
y = df["readmitted"]

print(X.shape)
print(y.shape)

(25000, 16)
(25000,)

---
# 📖 Step 5A: Encode the Target Variable
---

## 🎯 Objective

The target variable (`readmitted`) contains categorical values (`Yes` and `No`). Machine learning algorithms require the target variable to be in numerical format before training.

In this step, we use **LabelEncoder** to convert the target labels into numerical values.

This transformation is only applied to the target variable because it represents the class labels that the model must predict.

In [10]:
# ============================================================
# Step 5A: Encode the Target Variable
# ============================================================

from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder object
label_encoder = LabelEncoder()

# Encode target variable
y_encoded = label_encoder.fit_transform(y)

# Display first 10 encoded values
print("First 10 Encoded Values:")
print(y_encoded[:10])

# Display class mapping
print("\nClass Mapping:")
for i, class_name in enumerate(label_encoder.classes_):
    print(f"{class_name} --> {i}")

First 10 Encoded Values:
[0 0 1 1 0 1 0 1 1 0]

Class Mapping:
no --> 0
yes --> 1

## 🔍 Observations

The target variable has been successfully converted into numerical format using LabelEncoder.

The original class labels have been mapped as follows:

- No → 0
- Yes → 1

This transformation enables machine learning algorithms to interpret the target variable during training.

---
# 📖 Step 5B: One-Hot Encode the Categorical Features
---

## 🎯 Objective

Most machine learning algorithms cannot work directly with categorical (text) data. Therefore, categorical features must be converted into numerical representations.

In this step, we use **One-Hot Encoding**, which creates a separate binary (0 or 1) column for each unique category in a feature.

Unlike Label Encoding, One-Hot Encoding does not introduce any artificial order between categories, making it suitable for nominal categorical variables.

The encoded features will later be combined with the numerical features to create the final dataset for model training.

In [11]:
# ============================================================
# Step 5B: One-Hot Encode the Categorical Features
# ============================================================

from sklearn.preprocessing import OneHotEncoder

# Identify categorical columns
categorical_columns = X.select_dtypes(include=["object", "string"]).columns

# Create OneHotEncoder
encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

# Fit and transform categorical features
X_categorical_encoded = encoder.fit_transform(X[categorical_columns])

# Convert to DataFrame
encoded_df = pd.DataFrame(
    X_categorical_encoded,
    columns=encoder.get_feature_names_out(categorical_columns)
)

# Display shape
print("Encoded Data Shape:", encoded_df.shape)

# Display first five rows
encoded_df.head()

Encoded Data Shape: (25000, 47)

,age_[40-50),age_[50-60),age_[60-70),age_[70-80),age_[80-90),age_[90-100),medical_specialty_Cardiology,medical_specialty_Emergency/Trauma,medical_specialty_Family/GeneralPractice,medical_specialty_InternalMedicine,...,glucose_test_high,glucose_test_no,glucose_test_normal,A1Ctest_high,A1Ctest_no,A1Ctest_normal,change_no,change_yes,diabetes_med_no,diabetes_med_yes
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

## 🔍 Observations

The categorical features have been successfully transformed into numerical format using One-Hot Encoding.

The encoded dataset contains:

- **25,000 observations (rows)**
- **47 encoded categorical features (columns)**

Each unique category has been converted into a separate binary feature containing values of either **0** or **1**.

For example:

- The `age` feature has been expanded into multiple age-group columns.
- The `medical_specialty` feature has been converted into separate specialty-specific columns.
- Binary categorical variables such as `change` and `diabetes_med` have been represented using two binary columns.

This transformation preserves the categorical information while avoiding any artificial ordering between categories.

## 📌 Conclusion

The categorical input features have been successfully encoded into numerical representations using One-Hot Encoding. These encoded features are now suitable for machine learning algorithms.

The next step is to preprocess the numerical features by applying feature scaling before combining both numerical and encoded categorical data.

---
# 📖 Step 5C: Scale the Numerical Features
---

## 🎯 Objective

Numerical features in a dataset often have different value ranges. For example, one feature may range from 1 to 14, while another ranges from 1 to over 100. These differences can negatively affect the performance of many machine learning algorithms.

To overcome this issue, numerical features are standardized using **StandardScaler**.

StandardScaler transforms each numerical feature so that:

- The mean becomes approximately **0**.
- The standard deviation becomes approximately **1**.

This ensures that all numerical features contribute equally during model training and improves the convergence of several machine learning algorithms.

In [12]:
# ============================================================
# Step 5C: Scale Numerical Features
# ============================================================

from sklearn.preprocessing import StandardScaler

# Identify numerical columns
numerical_columns = X.select_dtypes(include=["number"]).columns

# Create StandardScaler object
scaler = StandardScaler()

# Scale numerical features
X_numerical_scaled = scaler.fit_transform(X[numerical_columns])

# Convert NumPy array to DataFrame
scaled_df = pd.DataFrame(
    X_numerical_scaled,
    columns=numerical_columns
)

# Display shape
print("Scaled Numerical Data Shape:", scaled_df.shape)

# Display first five rows
scaled_df.head()

Scaled Numerical Data Shape: (25000, 7)

,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency
0,1.181671,1.451151,-0.205440,0.216814,1.366510,-0.522918,-0.210644
1,-0.484212,-0.466276,0.377601,-0.403505,-0.306494,-0.522918,-0.210644
2,0.182141,0.088769,-0.788481,0.216814,-0.306494,-0.522918,-0.210644
3,-0.817389,-0.365359,-0.788481,-0.527569,0.530008,-0.522918,-0.210644
4,-1.150566,-0.062607,-0.788481,-1.147888,-0.306494,-0.522918,-0.210644

## 🔍 Observations

The numerical features have been successfully standardized using **StandardScaler**.

The scaled dataset contains:

- **25,000 observations (rows)**
- **7 numerical features (columns)**

After scaling:

- Each numerical feature has a mean close to **0**.
- Each numerical feature has a standard deviation close to **1**.

The original relationships between observations are preserved while ensuring that all numerical features are on the same scale.

This preprocessing step is particularly beneficial for machine learning algorithms that are sensitive to feature magnitudes, such as Logistic Regression, Support Vector Machines (SVM), K-Nearest Neighbors (KNN), and Neural Networks.

## 📌 Conclusion

The numerical features have been successfully standardized using StandardScaler.

The scaled numerical dataset is now ready to be combined with the encoded categorical features to create the final machine-learning-ready dataset.

---
# 📖 Step 5D: Combine Scaled Numerical and Encoded Categorical Features
---

## 🎯 Objective

After preprocessing, the numerical and categorical features exist as separate datasets.

To prepare the data for machine learning, these transformed features must be combined into a single feature matrix.

The final dataset produced in this step contains:

- Standardized numerical features.
- One-Hot Encoded categorical features.

This combined dataset will serve as the input for machine learning model training.

In [13]:
# ============================================================
# Step 5D: Combine Numerical and Categorical Features
# ============================================================

# Combine numerical and categorical features
X_processed = pd.concat(
    [scaled_df, encoded_df],
    axis=1
)

# Display shape
print("Processed Dataset Shape:", X_processed.shape)

# Display first five rows
X_processed.head()

Processed Dataset Shape: (25000, 54)

,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,age_[40-50),age_[50-60),age_[60-70),...,glucose_test_high,glucose_test_no,glucose_test_normal,A1Ctest_high,A1Ctest_no,A1Ctest_normal,change_no,change_yes,diabetes_med_no,diabetes_med_yes
0,1.181671,1.451151,-0.205440,0.216814,1.366510,-0.522918,-0.210644,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,-0.484212,-0.466276,0.377601,-0.403505,-0.306494,-0.522918,-0.210644,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.182141,0.088769,-0.788481,0.216814,-0.306494,-0.522918,-0.210644,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,-0.817389,-0.365359,-0.788481,-0.527569,0.530008,-0.522918,-0.210644,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,-1.150566,-0.062607,-0.788481,-1.147888,-0.306494,-0.522918,-0.210644,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

## 🔍 Observations

The scaled numerical features and One-Hot Encoded categorical features have been successfully combined into a single processed dataset.

The final processed dataset contains:

- **25,000 observations (rows)**
- **54 input features (columns)**

The first seven columns represent standardized numerical features, while the remaining forty-seven columns represent One-Hot Encoded categorical features.

All features are now numerical, making the dataset compatible with machine learning algorithms.

The preprocessing steps have preserved the original information while transforming the data into a format suitable for model training.

## 📌 Conclusion

The preprocessing phase has been completed successfully.

The original dataset has been transformed into a machine-learning-ready feature matrix containing standardized numerical features and encoded categorical features.

The processed dataset is now ready to be divided into training and testing subsets for model development.

---
# 📖 Step 6: Split the Dataset into Training and Testing Sets
---

## 🎯 Objective

Before training a machine learning model, the dataset must be divided into two subsets:

- **Training Set** – Used by the model to learn patterns from the data.
- **Testing Set** – Used to evaluate the model on unseen data.

This helps measure how well the model generalizes to new data and prevents overfitting.

In this project:

- **80%** of the data is used for training.
- **20%** of the data is reserved for testing.

The `stratify` parameter is used to preserve the original class distribution in both the training and testing datasets.

In [14]:
# ============================================================
# Step 6: Train-Test Split
# ============================================================

from sklearn.model_selection import train_test_split

# Split the processed dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_processed,
    y_encoded,
    test_size=0.20,
    random_state=42,
    stratify=y_encoded
)

# Display dataset shapes
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (20000, 54)
Testing Features  : (5000, 54)
Training Labels   : (20000,)
Testing Labels    : (5000,)

## 🔍 Observations

The processed dataset has been successfully divided into training and testing subsets.

The dataset split resulted in:

- **Training Features:** 20,000 observations with 54 processed features.
- **Testing Features:** 5,000 observations with 54 processed features.
- **Training Labels:** 20,000 target values.
- **Testing Labels:** 5,000 target values.

An 80:20 split was used, providing sufficient data for model training while reserving an independent dataset for performance evaluation.

The `stratify` parameter ensured that the distribution of the target classes (`Yes` and `No`) remained approximately the same in both the training and testing datasets.

## 📌 Conclusion

The dataset has been successfully divided into training and testing subsets.

The training dataset will be used to train machine learning models, while the testing dataset will be used to evaluate how well the trained models generalize to unseen patient data.

The dataset is now fully prepared for model development.

In [16]:
processed_df = X_processed.copy()

processed_df["readmitted"] = y_encoded

In [19]:
processed_df.to_csv("../data/processed/processed_dataset.csv", index=False)

print("Saved Successfully")

Saved Successfully